### ISSUE TITLE
how to disable the headless browser to load images?

### ISSUE THREAD

**Issue by winzenith** [OnetapInc/chromy#1]
First of all, thanks for creating this great tool for manipulating the browser api easily, and sorry i am just a newbie, and i wonder what should I do to disable the headless browser to load images ? and is it possible to wrap that sort of relevant event as a function ? 
I've researched the document https://chromedevtools.github.io/devtools-protocol/tot/Page/ , and i have no cue where is the right direction may meet my demand. I hope there's a way to solve it. and I'll appreciate if this could be supported. thank you

**Comment by dotneet** [comment]
Hi winzenith

You can use `blockUrls()` to solve your problem.

```js
const Chromy = require('chromy')

let chromy = new Chromy({visible: true})
chromy.chain()
      .blockUrls(['*.png', '*.jpg', '*.jpeg', '*.gif'])
      .goto('https://example.com/')
      .sleep(10000)
      .end()
      .then(_ => chromy.close())
      .catch(_ => chromy.close())
```

**Comment by winzenith** [comment]
ＴＨＡＮＫ

**Comment by winzenith** [comment]
Hi dotneet, It works and supported very well, thanks so much !
