### ISSUE TITLE
Update chrome-remote-interface

### ISSUE THREAD

**Issue by tiberiuzuld** [OnetapInc/chromy#100]
✗ High severity vulnerability found on ws@2.0.3
- desc: Denial of Service (DoS)
- info: https://snyk.io/vuln/npm:ws:20171108
- from: project@2.0.4 > chromy@0.5.8 > chrome-remote-interface@0.23.3 > ws@2.0.3

Seems to be fixed in ws@3.3.1 or higher which chrome-remote-interface has in the latest version 0.25.5
https://github.com/cyrus-and/chrome-remote-interface/blob/master/package.json

**Comment by dotneet** [comment]
Thank you for reporting.

I've published new version of chromy to fix that problem.
Please check it.

**Comment by tiberiuzuld** [comment]
all looks good now.
Thanks
