### ISSUE TITLE
Latest npm package (0.5.9) has wrong code published

### ISSUE THREAD

**Issue by markmsmith** [OnetapInc/chromy#103]
I was trying to follow the example to set cookies on a connection, which includes a call to getCookies() to confirm they're set:
https://github.com/OnetapInc/chromy/blob/master/examples/cookie.js#L10
and in the 0.5.9 tag of the codebase we can see that the getCookies() method exists:
https://github.com/OnetapInc/chromy/blob/v0.5.9/src/index.js#L786
However, if you open up the same file in the dist folder published on npm, you'll see that getCookies() is missing:
~/<project>/node_modules/chromy/dist/index.js

I'm guessing  the dist folder wasn't rebuilt before publishing, so the npm module version and code are out of sync.

**Comment by dotneet** [comment]
@markmsmith Thank you for reporting!
maybe you are right. 
I've published 0.5.10. please check it.

**Comment by markmsmith** [comment]
Yup, I'm seeing getCookies within the package now, thanks!  
I'll close this issue, but it might make sense to tag the repo with 0.5.10 as well (even though there's no new commits) just to keep the npm and code versions in sync.
