### ISSUE TITLE
chromy not closing chrome.app instance?

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#11]
@dotneet Hi.  What exactly is the command that should close chrome?  When my script is complete I still have chrome processes running.   Thank you!

**Comment by dotneet** [comment]
Please use close() or [Chromy.cleanup()](https://github.com/OnetapInc/chromy#static-cleanup) command before NodeJS process is finished.

**Comment by garris** [comment]
Hmmm.  So, here is my scenario.  My script opens multiple instances of chromy and they all start taking multiple screenshots. I want each one to close when they are finished their job.  

So imagine a multiple sceenshotElement().result() pattern terminating with an .end().close()

In my case, my chrome instances are still all open when all the chains have terminated.

Would love an opinion if you have a chance. 

Thanks.

**Comment by garris** [comment]
The implementation is here. 
https://github.com/garris/BackstopJS/blob/ae30f79cd8e928ad42f42a3bde817017cc51df02/core/util/runChromy.js#L72-L76

**Comment by dotneet** [comment]
I found that the code has two problems.

1. chromy variable is not chromy instance but chain object.
chain object's action is called after end() is called.
thus, need to write chromy.close().end().

2. single chromy instance must be used synchronously.
That code make single chromy instance to execute multiple process in parallel.
This behavior causes unexpected result. 

I wrote sample code.

https://github.com/dotneet/BackstopJS/blob/backstop-chromy-working/core/util/runChromy.js#L275

And, as I've fixed screenshotSelector's bug, update chromy.

**Comment by garris** [comment]
Thank you very much for the code sample -- this looks great!   I like that next() pattern to keep everything synchronous -- you have very clean coding style 😸.

I will run this tonight after work and share the results.   

ありがと!

**Comment by dotneet** [comment]
どういたしまして！
Actually when I found next pattern() I was very pleased!😁

**Comment by garris** [comment]
Just an update.  I tried using your code suggestion but the issue is still not resolved.  I started looking at your chain() method but ran out of time.   

My next step is to try to solve this issue outside of backstop.  I will create a separate "pure" chromy script (outside of backstopjs) which will simulate the same kind of "assembly" pattern we use in backstop.  This will eliminate any issue which could be happening with chromy inside of backstop and help me to understand/experiment with creating a "pure" chromy script that synchronously generates a variable number of screen captures and evaluate steps. 

Unfortunately -- I just got very busy at work so I may not be able to make progress for a few days.  I will update you when I have new information.  I am pretty sure we will figure this out -- thanks for all your help!

**Comment by dotneet** [comment]
I tested my sample code with default backstop configuration that is generated by `backstop genConfig`.
In my environment, All chrome browsers are closed after it took screenshot.

Environemnt:
 - MacOS
 - Chrome 60 (Beta)
 - set engine in configuration to 'chromy'.

I ran `./cli/index.js test` and all browser is closed normally. but reporting process is crashed.

Could you tell me your environment and sample configuration that can reproduce this problem.

**Comment by garris** [comment]
Hmm.  Well that is good news.  As I said -- I really didn't have enough time to do a good job testing.    Perhaps I made a mistake and it will just work the second time?

I was also using the default configuration on MacOS.   The only difference is that I was running the global instance i.e. `backstop test`.  I don't think this should be an issue.  It's more likely that I was rushed and simply made an integration mistake.  Please give me a chance to reimplement your changes into my branch again and I will report back!   Thank you.

**Comment by garris** [comment]
Also -- the reporting crash is expected behavior at this point.

**Comment by dotneet** [comment]
OK.
I'm wait for your update.

I tested some times with below repository. (My sample code I already posted) 
https://github.com/dotneet/BackstopJS/tree/backstop-chromy-working

Good luck!

**Comment by dotneet** [comment]
I possibly figure out the problem of your code.
To close browsers normally, the two problems I mentioned must be resolved at same time.
If you didn't resolve the problem about parallel processing, browsers are perhaps not closed.
The communication with a browser broke by receiving many commands in parallel.
Because of that, close() is failed.
I hope this helps you.

**Comment by garris** [comment]
OK!   Yes,  I think the issue was my fault.  After updating chromy everything is working!  It is behaving very very nicely. 

I will fix the downstream tests to get them running again and start working to add back the features which are commented out.  I am sure I will be contacting you soon with questions and possible bugs.  But for now the progress is excellent!

Thank you for all of your help!

**Comment by dotneet** [comment]
That's good!
I'm happy to hear that!

**Comment by garris** [comment]
All good here.  Closing issue.

FWIW: Integration status here...
https://github.com/garris/BackstopJS/issues/454#issuecomment-310870229
