### ISSUE TITLE
npm install chromy fails

### ISSUE THREAD

**Issue by NimaSoroush** [OnetapInc/chromy#12]
Hi,

Just tried to install chromy and got this error:

```
npm install chromy
npm ERR! code ETARGET
npm ERR! notarget No matching version found for async-chain-proxy@^0.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'chromy'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/y/.npm/_logs/2017-06-26T14_56_42_085Z-debug.log
```

For some reason, it can't find `async-chain-proxy` with that version? any idea?

**Comment by dejay12** [comment]
latest version appears to be ^0.1.2

but on Chromy package.json it is ^0.1.3

I downloaded the zip and changed to 0.1.2 and ran npm install

**Comment by NimaSoroush** [comment]
@dotneet : is this something going to be fixed soon?

**Comment by Primajin** [comment]
Yeah I'm experiencing the same problem. Using yarn I can interactively choose 0.1.2 but that doesn't work on the CI system.

**Comment by dotneet** [comment]
Sorry, I forgot to publish async-await-chain.
I now published 0.1.3. please npm install again.

**Comment by Primajin** [comment]
Should be good to go now, @NimaSoroush can you verify?

**Comment by NimaSoroush** [comment]
@dotneet @Primajin : Works fine now. Thanks

**Comment by NimaSoroush** [comment]
Hi @dotneet : what is the node version requirement to run chromy?

**Comment by dotneet** [comment]
Hi @NimaSoroush 
Chromy requires node 7.6 or later because of using async/await keyword.

**Comment by NimaSoroush** [comment]
Hi @dotneet,
is that ok if we run add compatibility to elder version through babel?
I wanted to run chromy in one of out pipelines which uses node6.9 and we can't update node version there.

**Comment by dotneet** [comment]
Basically I agree with this suggestion.
But I can't imagine how you do it.
Could you tell me that?

**Comment by NimaSoroush** [comment]
Hi @dotneet:

Just created this PR to discuss how we would approach this. https://github.com/OnetapInc/chromy/pull/19

The same change should apply to https://github.com/OnetapInc/async-chain-proxy too

already tested this locally and works as expected with node 6.9 and npm 4.

**Comment by dotneet** [comment]
Thanks!
I understood your approach.
I commented PR!
