### ISSUE TITLE
Upload/Download File

### ISSUE THREAD

**Issue by dejay12** [OnetapInc/chromy#13]
Sorry if wrong place I am new to github/programming

Is it possible to upload, like say nightmare-upload?

great library,thanks

**Comment by dotneet** [comment]
Hi @dejay12,

Currently chromy does not support method of uploading file easily.
But it might be able to implemented.
I'll implement it in the near future.

If you want to implement soon, below issue maybe helps you.

https://github.com/cyrus-and/chrome-remote-interface/issues/164

Chromy wrapped chrome-remote-interface and you can access it like this:

```
const Chromy = new Chromy()
const client = chromy.client
const {DOM, Runtime} = client
```

**Comment by dotneet** [comment]
Hi @dejay12,

I've just added setFile() command to Chromy.
This command sets file or files to file control.
This is what you want right?

Here is example:

```js
const Chromy = require('../src')
const path = require('path')

let chromy = new Chromy({visible: true})
chromy.chain()
      .goto('http://localhost/'))
      .setFile('input[type="file"]', __filename)
      .click('button.submit')
      .sleep(3000)
      .end()
      .catch(e => {
        console.log(e)
      })
      .then(_ => chromy.close())
```

**Comment by dejay12** [comment]
Wow, thank you very very much for this
