### ISSUE TITLE
Maintain 1:1 @72ppi resolution?

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#14]
Is it be possible to ensure screenshots are captured at lower resolution -- even on high-resolution devices?   Possibly through the emulation setting?

**Comment by dotneet** [comment]
Does "lower resolution" mean resolution of browsers's viewport?

If you mean so, I think it can be implemented with either of two ways.

1. Emulates device scale factor.

Chrome has the way to override device scale factor. 
https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride

Perhaps Chromy would provide the solution for the issue's problem by this setting.

2. Scale to lower resolution.

If above solution cannot be realized, simply Chromy scale down.

**Comment by garris** [comment]
So, the use case is this...

- I create references on my desktop -- which has standard resolution.  
- I later test on my laptop which has a retina (double resolution) screen.  This test fails because all the images are at the wrong scale.   So, I think it might be best to limit ALL image capture to the lower resolution (since higher resolution uses more disc space and does not produce better tests.)

I am not sure which approach would be better?

**Comment by dotneet** [comment]
OK, I understood your use case.
It would be resolved with the solution I posted.

**Comment by garris** [comment]
Great -- but which solution 1 or 2?

**Comment by dotneet** [comment]
At first, I try solution 1.
If it was failed, I try solution 2.

**Comment by garris** [comment]
Ah!  I understand now.  Thank you.

**Comment by garris** [comment]
Ok.  The resolution enhancement is working great for screenshotMultipleSelectors() -- however -- I still have use-cases where I am using `.screenshot().result(...)` to emulate scrolling and other page-viewport related scenarios.  How can I ensure that `.screenshot()` also captures at 72ppi resolution?

**Comment by dotneet** [comment]
I intend to add an option that specify resolution of result to screenshot() and screenshotXxx().
And I also intend to change declaration of these functions. These functions have many arguments as an optional parameter. It's annoying a little. I apply hash form option instead of many arguments.
Old form will be specified deprecated.

After these changes are implemented screenshot() can be called like this:

```js
    .screenshot()  // captures at browser resolution.
    .screenshot({keepDeviceResolution: true})  // captures at device resolution.
    
    .screenshot('png')  // deprecated.
```

**Comment by garris** [comment]
That sounds good.  What is the difference between device resolution and browser resolution?

**Comment by dotneet** [comment]
With high resolution device such as iPhone and Mac, the physical resolution is different to the logical resolution in browser context.
Device resolution means physical resolution.
Browser resolution means logical resolution in browser context.

Chromy uses `window.devicePixelRatio` to detect logical resolution in browser context.
https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

width with logical resolution = width with physical resolution / `window.devicePixelRatio`

**Comment by garris** [comment]
> width with logical resolution = width with physical resolution / window.devicePixelRatio
Ah, ok.  that helps.  Just a suggestion, you may want to call this property `useDeviceResolution` or `enableDeviceResolution`.  I assume that not including these properties will generate all images at `window.devicePixelRatio = 1` regardless of device?

**Comment by dotneet** [comment]
Thanks. I'll name this property `useDeviceResolution`.

Yes, If `useDeviceResolution` is set to false or undefined, chromy will generate all images that have the logical resolution in browser.

**Comment by garris** [comment]
Verified -- working as expected.
