### ISSUE TITLE
is chromy able to open a local file?

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#18]
I get this error...
`Error: Cannot navigate to invalid URL`

with this script...
```
const Chromy = require('chromy')
const path = require('path')
const fs = require('fs')

let chromy = new Chromy({chromeFlags: ['--window-size=600,400'], visible: true});
chromy
  .chain()
  .goto('examples/myCoolProject/index.html')
  .screenshotSelector('html')
  .result((png) => {
    fs.writeFileSync('./chromyTest.png', png)
  })
  .end()
  .then(_ => chromy.close())
  .catch(e => {
    console.log(' ' + e);
    chromy.close();
  });
```

**Comment by dotneet** [comment]
Currently, to open a local file, chromy need absolute url like this:

```js
chromy.chain().goto('file:///Users/username/workdir/index.html')
```

I think relative url meaning local file path is useful.
I'll implement in the near future.

**Comment by garris** [comment]
Thanks.

**Comment by dotneet** [comment]
It have been implemented. Please check out latest version of chromy.

**Comment by garris** [comment]
That was fast!   I am about to go on vacation for a week (US holiday).   It may take some time to review.  Cheers!

**Comment by dotneet** [comment]
OK! Have a nice vacation!

**Comment by garris** [comment]
Works!  Thank you!
