### ISSUE TITLE
When i start Chromy in invisible mode i can see a frame of browser

### ISSUE THREAD

**Issue by Rznk** [OnetapInc/chromy#2]
let Chromy = require('chromy');

let chromy = new Chromy();
chromy.chain()
    .goto('https://www.google.com/')
    .evaluate(() => {
        return document.getElementById('textfield-1012-labelEl').innerText;
    })
    .result((r) => console.log(r))
    .end()
    .then(() => chromy.close())

When i launch this code i see a frame of browser and then it disappears.

**Comment by dotneet** [comment]
@Rznk 
Hi Rznk

Please check whether your machine installed Chrome 59 or later.
headless mode is supported in Chrome 59 or later.

Chromy automatically search for executable of Chrome on your machine and bootstrap it.

**Comment by Rznk** [comment]
Yeap. Had to relaunch my Chrome and it worked. What about linux? It will search for Chrome the same way?

**Comment by dotneet** [comment]
Yes. Chromy can find out Chrome even Linux in most situation.
This functionality is provided by [Lighthouse](https://github.com/GoogleChrome/lighthouse).

**Comment by Rznk** [comment]
Thanks for great functionality and for help
