### ISSUE TITLE
solved -- Error: 'Emulation.resetViewport' wasn't found

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#26]
looks like `screenshotMultipleSelectors()` may be broken?

$ node -v
v8.1.0

error:
```
~/Desktop/backstop test @gshipon-mn1(gshipon)
$ node chromyTest
error caught > Error: 'Emulation.resetViewport' wasn't found
```

script:
```
chromy
  .chain()
  .console(function (text, consoleObj) {
    if (console[consoleObj.level]) {
      console[consoleObj.level]((consoleObj.level).toUpperCase() + ' > ', text);
    }
  })
  .goto('examples/featureTests/index.html')
  .wait(1)
  .screenshotMultipleSelectors(
    ["body", "h1", "h2"],
    handlescreenshots,
    {useQuerySelectorAll: true}
  )
  .end()
  .then(_ => {
    chromy.close()
    console.log('success');
  })
  .catch(e => {
    chromy.close()
    console.log('error caught > ' + e);
  });


function handlescreenshots(error, png, index, selectors, sub){
  console.log('>>>',error, selectors[index], sub);
  fs.writeFileSync(`./screens/${selectors[index]}_${sub}.png`, png);
}

```

**Comment by garris** [comment]
I have tried chromy 0.3.1,  0.3.2, 0.3.3 all return the same response. 😔

**Comment by garris** [comment]
@dotneet  Found the issue!  Chrome Canary was throwing the error.  v61.0.3155.0
Don't know if that command was deprecated.  Thought you'd want to know.

**Comment by dotneet** [comment]
Thanks. I confirmed that that command will remove in future and discover alternative way.
I'll support both versions canary and stable.

**Comment by dotneet** [comment]
@garris 
I opened the issue that related to this problem at chromium 3 days ago.
https://bugs.chromium.org/p/chromium/issues/detail?id=741969

I've published new version of chromy that supports chrome61, but chrome's bug was fixed yesterday.
So maybe you need to update chrome canary.

**Comment by garris** [comment]
will do.  thanks!
