### ISSUE TITLE
bypassing -- Your connection is not private error

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#27]
Is there a programatic way to get past this screen.  This will be another big issue for other developers.

![image](https://user-images.githubusercontent.com/447033/28143524-d8cac6b2-671a-11e7-8551-e9501435656b.png)

**Comment by dotneet** [comment]
does "get past this screen" means ignoring security warning?

**Comment by garris** [comment]
Yes!  😄

**Comment by garris** [comment]
Sorry for confusing language!

**Comment by kensoh** [comment]
I don't have a site that can test this, not sure if any of the security / SSL related switches below can help, which can be triggered during launch time. https://peter.sh/experiments/chromium-command-line-switches/

**Comment by dotneet** [comment]
@kensoh thank you for your advice.

@garris Seeing the site mentioned by @kensoh, I found the switch that helps to resolve the problem. `--ignore-certificate-errors` might be your help.

**Comment by garris** [comment]
Great -- I will try adding that to chrome flags.  Thank you!

**Comment by garris** [comment]
Yes.  I can confirm that both methods eliminate the security wall.

This is the BEST option...
```
chromy.chain()
   .ignoreCertificateErrors()  
   ...
```

Adding this also works... 
```
--ignore-certificate-errors
```
**but**  if you **also** enable the "window" option the following warning appears (does not appear in a screenshot if the window option is false)
![image](https://user-images.githubusercontent.com/447033/29223182-81d9b15c-7e7a-11e7-9370-bad141e8423d.png)

**Comment by garris** [comment]
Thanks for addressing this!
