### ISSUE TITLE
how do I set screenshot size?

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#3]
Hi -- thanks for starting this project -- it is very cool!

1)  How would I set the size of the screenshot?  

2) Also, Can you explain why my PDF and PNG screenshots are different for the following example?

```
const Chromy = require('chromy')
const path = require('path')
const fs = require('fs')

let chromy = new Chromy()
chromy.chain()
      .goto('https://google.com/')
      .screenshot()
      .result((png) => {
        fs.writeFileSync('out.png', png)
      })
      .pdf()
      .result((pdf) => {
        fs.writeFileSync('out.pdf', pdf)
      })
      .end()
      .then(_ => chromy.close())
      .catch(e => chromy.close())
```
results files attached... 

_the PDF captures the document size_
[out.pdf](https://github.com/OnetapInc/chromy/files/1064626/out.pdf)

_the PNG captures part of the document_
[out.png](https://user-images.githubusercontent.com/447033/26984320-ca1b312e-4cf3-11e7-9faa-9307718edbbf.png)

**Comment by dotneet** [comment]
Hi

> 1. How would I set the size of the screenshot?

size of screenshot is depend on window size.
You can change window size like this:

```js
let chromy = new Chromy({additionalChromeFlags: ['--window-size=320,240']})
```

Currently, Chromy doesn't supports changing window bounds after launched.

>2. Also, Can you explain why my PDF and PNG screenshots are different for the following example?

I think that PDF is output as a printing image. 
.pdf() is the wrapper of [this](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF).

Thank you for trying Chromy.

**Comment by garris** [comment]
@dotneet -- thank you for your help!  I will give this a try.

I think Chromy could become very popular very quickly.   Are you planning to write any articles?

**Comment by dotneet** [comment]
@garris 
I hope so. I already published the article about the brief of Chromy on medium.
https://medium.com/@fgets/chromy-the-library-for-headless-chrome-c09cc95445b2

If you have any ideas of improving this article or this library, please let me know.

thanks.

**Comment by garris** [comment]
Thank you.  Closing issue.  Cheers!
