### ISSUE TITLE
support for printToPDF options

### ISSUE THREAD

**Issue by bhagn** [OnetapInc/chromy#31]
Currently, chromy.pdf() doesn't take any options. Is it possible to support the options supported by devtools?

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF

Being able to specify the page height, width, scale and other things would be really helpful.

**Comment by dotneet** [comment]
Hi @bhagn,

Exactly.  I will add options.

**Comment by dotneet** [comment]
Sorry, It's just a document problem.
chromy.pdf() can already take options.

I will fix readme.

**Comment by bhagn** [comment]
@dotneet Thanks for clarifying.

**Comment by bhagn** [comment]
@dotneet is there a way to control the width of the viewport when starting up?

**Comment by dotneet** [comment]
@bhagn 
There are two options.

1.  Using chromeFlags option, specify window size

```js
let chromy = new Chromy({chromeFlags: ['--window-size=320,240']})
```

2.  Use emulation.

This example will be help.
https://github.com/OnetapInc/chromy/blob/master/examples/custom_emulate.js

**Comment by dotneet** [comment]
If you prefer to use emulation. Please update chromy to 0.3.5 (I've published just now.)

**Comment by bhagn** [comment]
Thanks a lot for the answers. Will try out 0.3.5

**Comment by dotneet** [comment]
If you get a problem, reopen this issue or open new issue.
