### ISSUE TITLE
capture viewport with screenshotMultipleSelectors()?

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#32]
Is it possible to use screenshotMultipleSelectors() to capture the viewport? 
chromy.screenshot() does have this behavior but the resolution is not normalized.  

Also,  It would be great if screenshotMultipleSelectors() could accept 'DOCUMENT' and 'BODY' "magic" selectors -- where DOCUMENT would capture the entire document and BODY would capture only the viewport.  _FWIW: This is a convention used in backstopjs_.

Do you have some thoughts?

**Comment by dotneet** [comment]
in latest version, chromy.screenshot() return lower resolution image.
If want high resolution, useDeviceResolution option can be used.

**Comment by garris** [comment]
Yes, I have to agree!  It is unnatural to have body mean viewport.   Thank you for implementing lower resolution in .screenshot().

**Comment by garris** [comment]
verified screenshot() resolution is working as expected.  Great!
