### ISSUE TITLE
Termination of Chrome process

### ISSUE THREAD

**Issue by nicolaivadim** [OnetapInc/chromy#34]
Chrome Launcher by default sets handleSIGINT to true which allow termination of chrome process on `Ctrl-C`.
I've tried to set this flag explicit, but no result.
Please advise any solution.

**Comment by dotneet** [comment]
Currently handleSIGINT can not be used in chromy.
I'll enable this option later.

handleSIGINT is the option of .launch function of chrome-launcher.
but chromy doesn't use .launch() but use Launcher class directly.

**Comment by nicolaivadim** [comment]
Great, thank you, I can help you with this if you'll wish.

**Comment by dotneet** [comment]
Thanks! I welcome PR always.
