### ISSUE TITLE
scrollTo is not documented

### ISSUE THREAD

**Issue by ChALkeR** [OnetapInc/chromy#38]
Looks like [.scrollTo()](https://github.com/OnetapInc/chromy/blob/master/src/document.js#L111-L115) exists, but is not yet documented in the [API](https://github.com/OnetapInc/chromy#api) section.

That is probably applicable to other methods as well, like `getPageOffset`.

**Comment by dotneet** [comment]
Thanks.
I'll add these functions to README.

**Comment by ChALkeR** [comment]
The anchor looks broken. `#scrollTox-y` and `#scrolltox-y` are not equivalent.

**Comment by dotneet** [comment]
fixed! Thanks!
