### ISSUE TITLE
Injecting scripts

### ISSUE THREAD

**Issue by SebastianEdwards** [OnetapInc/chromy#4]
Hi there,

Love the project. Currently migrating a service from nightmarejs to chromy and it's working great. Just wondering if you're planning on supporting an API similar to `Nightmare#inject` or if there is any way to achieve a similar result with the current API.

**Comment by dotneet** [comment]
Hi

Thank you for using chromy!
I just published new version 0.2.1 to support inject().

Please try it out.

Example:

```js
let Chromy = require('chromy');

let chromy = new Chromy({visible: true});
chromy.chain()
  .goto('https://example.com/')
  .inject('js', 'inject.js')
  .inject('css', 'inject.css')
  .evaluate('injectedFunc()')
  .sleep(5000)
  .end()
  .then(() => chromy.close())
  .catch((e) => {console.log(e); chromy.close()})
```

**Comment by SebastianEdwards** [comment]
Wow, thanks for the quick response on this. Truly above and beyond!

Seems to work well for trivial JS injection but something seems to be going awry when injecting larger scripts (such as jQuery). Not sure exactly what is happening but the output seems to be mangled in certain areas leading to syntax errors. See [this diff between the original file and the contents of the script innerHTML](https://www.diffchecker.com/Ot1p93IK). Could be some kind of file encoding fault. Any thoughts?

**Comment by dotneet** [comment]
Sorry, I made some mistakes on escaping.
I fixed this problem and published again.

**Comment by SebastianEdwards** [comment]
Seems to be working well now - thanks so much for supporting this!

**Comment by perumal** [comment]
Hi @SebastianEdwards, @dotneet 
Can you guide me on injecting an online script like www.domain.com/myscript.js instead of injecting an local offline script. 
Thank you
