### ISSUE TITLE
Type does not correctly escape double quotes

### ISSUE THREAD

**Issue by jonathanlking** [OnetapInc/chromy#40]
In the definition of `type`  (in src/index.js) the selector is wrapped in double quotes and is not escaped. If there are any unescaped double quotes in the selector name this causes chromy to crash. In all other functions (that I've seen) selectors are wrapped in single quotes and escaped using ` escapeSingleQuote` (from src/util.js).

Is there any reason why this is the case and could we change this?

**Comment by jonathanlking** [comment]
I propose the following change:

```
diff --git a/src/index.js b/src/index.js
index fd69cc1..59a24c3 100644
--- a/src/index.js
+++ b/src/index.js
 -14,7 +14,8 @@ const {
 } = require('./error')
 const {
   createChromeLauncher,
-  completeUrl
+  completeUrl,
+  escapeSingleQuote
 } = require('./util')
 
 let instances = []
 -310,7 +311,7 @@ class Chromy extends Document {
   }
 
   async type (expr, value) {
-    await this.evaluate('document.querySelector("' + expr + '").focus()')
+    await this.evaluate('document.querySelector(\'' + escapeSingleQuote(expr) + '\').focus()')
     const characters = value.split('')
     for (let i in characters) {
       const c = characters[i]
```

**Comment by dotneet** [comment]
Hi @jonathanlking,

Thank you for reporting and PR!
It's just a bug. I've merged your PRs.

Thanks.
