### ISSUE TITLE
opening HTML as data-uri

### ISSUE THREAD

**Issue by pkra** [OnetapInc/chromy#43]
First off, thanks for chromy!

Is there a way to open HTML given as a [data-URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)? 

For example, the following doesn't return anything:
 
```
chromy
    .chain()
    .goto('data:text/html,<h1>Hello%2C%20World!<%2Fh1>')
    .evaluate(() => {
        return document.body.innerHTML;

    })
    .result((r) => console.log(r))
```

This is not hard to work around (e.g., passing a string along and setting `body.innerHTML`) but it would be convenient to just open the data straight away.

**Comment by dotneet** [comment]
Hi @pkra,

Thank you for opening the issue.
It's just a bug.
I'll fix it in the next release.

**Comment by pkra** [comment]
Ah, that's great to hear - thanks, @dotneet!

**Comment by pkra** [comment]
Thanks!
