### ISSUE TITLE
'frame' object has no 'type()' function

### ISSUE THREAD

**Issue by flancer64** [OnetapInc/chromy#44]
I try to type some text into the field that is placed in iframe and I see that there is no 'type()' function available:
![image](https://user-images.githubusercontent.com/5052385/28834302-8a9074f8-76ea-11e7-94b1-f660e78e79f4.png)

This is my code:
```javascript
await chromy.iframe('iframe#braintree-hosted-field-number', frame => {

    console.log('We are inside.');
    frame.type('input[name=credit-card-number]', '4111111111111111');

});
```

I try to create test scenario for Magento e-commerce app.

**Comment by dotneet** [comment]
Hi @flancer64,

I've published new version to support this.
Please update and try it!

**Comment by flancer64** [comment]
Thanks, @dotneet. It works :)
