### ISSUE TITLE
activate tab by targetId

### ISSUE THREAD

**Issue by cjhuaxin** [OnetapInc/chromy#48]
Hi, in my project, the chromy has multiple tabs, I'm tring to change the activate tab by targetId.
this is my code:
```
let pages = await chromy.getPageTargets();
let targetPage = pages.filter(p => p.url.indexOf(someKeys) > -1)[0];
await chromy.Target.activateTarget({targetId: targetPage.targetId});
```
but I got some errors like this:
**`TypeError: Cannot read property 'activateTarget' of undefined`**

Is there any way to activate the other tab? Thanks in advance!

**Comment by cjhuaxin** [comment]
I found the solution, just add the **launchBrowser: false** option, this is code:
```
let pages = await chromy.getPageTargets();
let targetPage = pages.filter(p => p.url.indexOf(someKeys) > -1)[0];
chromy = await new Chromy({target: targetPage.targetId, activateOnStartUp: true, launchBrowser: false});
```
Thanks the [examples](https://github.com/OnetapInc/chromy/blob/e7219df53d21f1310a6be5fcf92ee2b9e3bb669c/examples/tab.js)

**Comment by dotneet** [comment]
That's good!
If you have another question open an issue anytime.
