### ISSUE TITLE
Error: Cannot navigate to invalid URL

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#49]
Just checking here -- is there a regression on relative paths?

I am getting this... `Error: Cannot navigate to invalid URL` When I use a relative path.

This is related to https://github.com/garris/BackstopJS/issues/485

**Comment by dotneet** [comment]
Ah... Sorry, maybe this might be a regression too.
Chromy 0.4.4 and 0.4.5 might have regressions so try to use 0.4.3.

**Comment by dotneet** [comment]
fixed this problem in 0.4.6.

**Comment by garris** [comment]
Yup -- verified!
