### ISSUE TITLE
Wait(selector) doesn't wait for selector

### ISSUE THREAD

**Issue by Rznk** [OnetapInc/chromy#5]
await chromy.wait('ul.x-list-plain');

I can see this element in browser. But Wait(selector) keeps waiting. Am i missing something?

**Comment by dotneet** [comment]
@Rznk 
Thank you for reporting.

I found problem with wait(selector).
I fixed it and published new version of chromy (0.2.3).
Please check it out.

**Comment by dotneet** [comment]
If you have any questions reopen this issue or create new issue.
