### ISSUE TITLE
regression?  with .wait(<selector>)

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#50]
Might be a regression here too?

After addressing #49 -- when testing with a script using wait(<selector>) the script hangs.

You can see this with https://github.com/garris/backstop-feature-tests 

Running the first scenario `noSelectors` hangs waiting for a selector -- testing `noSelectors_readyEvent` does work.

**Comment by dotneet** [comment]
Might be a regression.
In chormy 0.4.5, I changed wait() behavior.
I'll investigate this problem tomorrow.
Please use chromy 0.4.4 until a reason is found.

**Comment by dotneet** [comment]
Please try to use 0.4.3.

**Comment by garris** [comment]
Yes.  0.4.3 works fine.   Thanks for the response.

Perhaps you may need to add some acceptance tests to your release pipeline?   You can feel free to use the tests here...  https://github.com/garris/backstop-feature-tests     This does not test ALL chromy features -- but it does cover a lot of chromy api surface area.

For the time being I will pin backstopjs to a specific version of chromy and bump as needed.

Cheers!

**Comment by dotneet** [comment]
I found out a problem.
Chromy uses `document.body.querySelector()` in `wait(selector)`, so can't find a body element.
should have used `document.querySelector()`.

I already have unit tests but this problem could not be found.
I'll add some test cases and consider CI system.

**Comment by dotneet** [comment]
fixed. please try v0.4.6.

**Comment by garris** [comment]
Works!
