### ISSUE TITLE
watching network requests/responses

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#52]
I have a use case where I need to watch for a network response.  

I need to know the status code of a specific request and take action based on the response value. 

Is there support for this?

**Comment by dotneet** [comment]
Can this issue be resoleved with https://github.com/OnetapInc/chromy/issues/25#issuecomment-314795055 ?

**Comment by garris** [comment]
Ah yes!  I was looking for a reference to this -- this is perfect.  Thank you!
