### ISSUE TITLE
Rendering broken when using non-headless mode {visible: true}

### ISSUE THREAD

**Issue by laubsauger** [OnetapInc/chromy#53]
Hi @dotneet, 

i think this is on chromy but i can't be entirely sure:

**Reduced testcase:**

````javascript
const Chromy = require('chromy');

// not headless
let chromy = new Chromy({ visible: true });
//headless
// let chromy = new Chromy();

chromy.chain()
    .goto('http://github.com/')
    .sleep(500)
    .end()
    .then(() => chromy.close());
````
**This is how it looks:**
![image](https://user-images.githubusercontent.com/1301310/29210323-52ffdbcc-7e93-11e7-8c17-c8403a6dd209.png)

**Environment**:

Chrome 60
Chromy 0.4.7
Centos 7
Node 8

I think the problem occured first after updating from chrome59 to chrome60 but i can't be sure.
Headless Mode still works. But having the window visible helps a lot when working on complex test cases.
If i manually start chrome via `google-chrome --remote-debugging-port=9222` and then run a chrome-remote-interface script against it, everything works and the rendering seems fine. 

Reference: https://github.com/garris/BackstopJS/issues/479

**Comment by dotneet** [comment]
Hi @laubsauger,

I've tried to reproduce this problem with same environment but I could not reproduce.

Environment:
 - CentOS7( on VirtualBox/MacOSX)
 - Chrome60
 - Node v8.3.0
 - Chromy 0.4.7
 - Gnome

Do you have any thoughts of another reason?

**Comment by garris** [comment]
@laubsauger I am not able to produce this either.

Maybe related... I found using `--ignore-certificate-errors` flag did _sometimes_ cause a screenshot issue -- because of an onscreen notification.   I switched to `chromyChain.ignoreCertificateErrors()` method and have not had an issue since.

**Comment by laubsauger** [comment]
Thanks for trying to reproduce. 
Unfortunately i have no other idea what could be causing this. 
I've bumped node to 8.3.1 and reinstalled chrome (still same version) via yum but i get the same result.
I'm not using the `--ignore-certificate-errors` switch in this minimal testcase.

**Comment by dotneet** [comment]
disable-gpu flag affects a result?

```js
new Chrome({
  visible: true,
  chromeFlags: {
    '--disable-gpu'
  }
})
```

**Comment by laubsauger** [comment]
I just installed `google-chrome-unstable`@62.0.3178.0 and the problem is gone.

@dotneet I will test your suggestion anyway.
