### ISSUE TITLE
chromeFlag doesn't work

### ISSUE THREAD

**Issue by Rznk** [OnetapInc/chromy#6]
let chromy = new Chromy({visible:true, typeInterval:100, chromeFlags:['--disable-popup-blocking']});

Pop up blocking still works

**Comment by dotneet** [comment]
@Rznk 

I confirmed chromeFlags option is working.
chromeFlags is added recently.
Please update chromy and try it again.

If that problem is reproduced, let me know details.
Particulary I want to know version of Chromy and complete source code and html that can reproduce problem. If it possible.

**Comment by Rznk** [comment]
I've got:
Chromy: 0.1.27
Chrome: Version 60.0.3112.24 (Official Build) beta (64-bit)
Windows 10 Pro 64bit

**Comment by Rznk** [comment]
let Chromy = require('chromy');
let cookies = require('./cookies.js');
let cookiev4 = require('./cookieV4');
let fs = require('fs');




async function main(search) {
    let chromy = new Chromy({visible:true, typeInterval:100, chromeFlags:['--disable-popup-blocking']});
    await chromy.setCookie(cookies.cookie1);
    await chromy.setCookie(cookiev4.cookiev4);
    await chromy.setCookie(cookies.cookie2);
    await chromy.goto('Sorry it's test server');
    await chromy.sleep(500);
    let start = await chromy.evaluate(async () => {
       return await document.getElementById('#ux-startbutton-btnEl')
    });
    if (!start) { chromy = await login(chromy)}


    //------------Search
    await chromy.click('#ux-startbutton-btnEl');
    await chromy.mouseMoved(50, 214);
    await chromy.sleep(500);
    await chromy.click('a#menuitem-1051-itemEl');
    await chromy.sleep(500);
    await chromy.click('#button-1112');
    await chromy.sleep(500);
    await chromy.click('#checkboxfield-1106-inputEl');
    await chromy.sleep(200);
    await chromy.type('#axs-dry-dList-Vessel-1110-inputEl', search);
    await chromy.sleep(500);
    await chromy.evaluate(()=>{
        let element = document.getElementById('axs-dry-dList-Vessel-1110-inputEl');
        let evt = new KeyboardEvent("keyup");
        element.dispatchEvent(evt);
    });
    await chromy.sleep(1000);
    await chromy.evaluate(()=> {
        let count = document.getElementsByClassName('x-boundlist-item').length;
        for (let x=0; x < count; x++){
            document.getElementsByClassName('x-boundlist-item')[x].click()
        }
    });

    await chromy.sleep(1000);
    await chromy.close()
}

async function login(chromy) {
    let v4Cookie;
    await chromy.wait(500);
    await chromy.type('#textfield-1011-inputEl', 'SORRY');
    await chromy.type('#textfield-1012-inputEl', 'SORRY');
    await chromy.click('div.x-btn');
    await chromy.wait(500);
    let cookiesNew = await chromy.evaluate(()=>{
        return document.cookie.split(';');
    });
    cookiesNew.forEach((item)=>{
        v4Cookie = (item.match(/axsmarineV4/i))
    });
    v4Cookie = v4Cookie.input.trim().split('=')[1];
    let wholeCookieFile = "let b = {'url':'SORRY', 'name':'vvv', 'value':'" + v4Cookie + "','expirationDate': 1528537469, domain:'SORRY'}; exports.cookiev4 = b;";
    fs.writeFileSync('./cookieAxsV4.js', wholeCookieFile);
    return chromy;
}

main('polar');

**Comment by dotneet** [comment]
Please update chromy to latest version(v0.2.3)
chromeFlags is supported since 0.2.0.
Sorry for insufficient documentation.

**Comment by dotneet** [comment]
If you have any questions reopen this issue or create new issue.
