### ISSUE TITLE
text anti-aliasing inconsistent across environments

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#61]
@dotneet This one has been coming up now for a lot of developers.  

Do you know why bitmaps taken on my retina laptop would render different text anti-aliasing when attaching non-retina monitors?

Could this have something to do with the process you use to maintain 1:1 resolution across different configurations? 

Here are two images taken on the same machine.  The reference was created on my laptop -- the test was created on my laptop with an external (non-retina) monitor attached...
![image](https://user-images.githubusercontent.com/447033/29579503-e5b89e62-8727-11e7-8c7d-029dc159bda5.png)

**Comment by dotneet** [comment]
When attaching retina monitor Chromy uses the Jimp library to resize an image.

I've added .setDeviceScaleFactor() in v0.5.1 @beta .
This command force Chrome to display in same pixel ratio always.
Currently I have not enough time to test it with BackstopJS.
So I'm not sure this approach works well. But worth to try.

If works, in backstop case, this command would also resolve screenshot performance issue caused by Jimp.

**Comment by garris** [comment]
How do I use `.setDeviceScaleFactor()`?

Like this
```
chromy.chain()
  .setDeviceScaleFactor()
  .goto()
  ...
```
Like that?  ^^^

**Comment by dotneet** [comment]
```js
.setDeviceScaleFactor(1)
```

**Comment by garris** [comment]
And with this set to 1, Jimp will not try to rescale?

**Comment by dotneet** [comment]
Yes. Jimp is not called after `.setDeviceScaleFactor(1)` is called.
Resizing is achieved by Chrome's emulation feature.

**Comment by garris** [comment]
Ok.  Will try this and let you know how it goes.  Thanks!

**Comment by garris** [comment]
@dotneet So, huge improvement!   But we still have a curious issue...
![image](https://user-images.githubusercontent.com/447033/29594507-5498c6ac-8766-11e7-85cd-1163e9cc4593.png)

Do you have any thoughts?

**Comment by garris** [comment]
So, mixed results...

- .screenshotMultipleSelectors() is still failing
- .screenshot() is now working

Hopefully you can apply the same fix to screenshotMultipleSelectors() ?

See images below... 

**screenshotMultipleSelectors()**
![image](https://user-images.githubusercontent.com/447033/29599745-a7a14926-8786-11e7-885f-2e0380eb75bc.png)

----------

**screenshot()**
![image](https://user-images.githubusercontent.com/447033/29600015-38646186-8788-11e7-89a9-c7a6849a715d.png)

**Comment by garris** [comment]
Here is another part of the test.

The actual file dimensions is off.  Rounding error or perhaps a bug?

In Backstop, every pixel value is compared,  1:1 file is required.  It can not be resampled.

The borders in the image are 1px
![image](https://user-images.githubusercontent.com/447033/29600291-dc2de0c0-8789-11e7-9e91-7e7edd284b64.png)

**Comment by garris** [comment]
Hi @dotneet,  I wanted to check and see if you have any thoughts about this one?

**Comment by dotneet** [comment]
Sorry, I've overlooked your comments.

I've improved the process for scaling in v0.5.2@alpha.
Could you test it whether this the change fix this problem.

**Comment by garris** [comment]
nice!  Checking right now...

**Comment by garris** [comment]
@dotneet  sadly no -- did not change anything 😢.    

Did you observe the above results?   Is the processing between the above capture methods different?

**Comment by dotneet** [comment]
.screenshotMultipleSelectors() uses full screen emulation but .screenshot() does not.
I've arranged test environments and confirmed that the problem reproduced.
Please wait for next report. But now I'm working on my job so I can't do this soon.

**Comment by garris** [comment]
Ok.  I understand.  Best wishes with your work.

I'll wait for your next report.  Thank you.

**Comment by dotneet** [comment]
@garris I've investigated this problem for several hours, but I can't find out a solution.
I think this results is caused by difference of processes that generate an image.
If my thoughts is correct, resolving this problem is very difficult.
With high resolution screen, to generate same resolution results Chrome need to scale down an image by scaling algorithm. On the other side,  with low resolution screen, Chrome don't need to scale an image. What Chrome should do is only capturing the image that is displayed on itself.
So, by the difference of processes, these results become different images regardless of same size.

**Comment by dotneet** [comment]
Possibly I found out the solution!
Please wait some times.

**Comment by dotneet** [comment]
@garris please try to add '--force-device-scale-factor=1' to chromeFlags. In my environments, this flag resolved the problem.

**Comment by garris** [comment]
Yes -- this is GREAT!   You have discovered the solution to the size ratio problem! 😺

**Comment by garris** [comment]
...But interestingly...  I am so sorry to report a new issue has appeared!

My guess is that monitor color profile is now causing an issue. In this example there is a large green area on the screen.  When referenced on my 72ppi monitor and tested with my retina laptop I get the following diff where all areas of color are slightly different...

![image](https://user-images.githubusercontent.com/447033/29723195-83dd27f0-8978-11e7-863b-b45612db85af.png)

It seems that chrome-headless delegates to hardware for rendering pretty significantly.  Have you seen anything about how "software-only" rendering could be used with chrome?    

In the meantime, perhaps changing monitor profiles will help?

**Comment by garris** [comment]
Thank you for fixing this!   I will create a new ticket for the new issue ^^^

**Comment by garris** [comment]
fixes https://github.com/garris/BackstopJS/issues/504
