### ISSUE TITLE
Chromy with headless shell

### ISSUE THREAD

**Issue by kiran-redhat** [OnetapInc/chromy#63]
Hey, can we drive headless shell (https://github.com/adieuadieu/serverless-chrome/blob/develop/packages/lambda/chrome/chrome-headless-lambda-linux-60.0.3095.0.zip) with chromy? I am planning to use headless shell to run backstopJS tests on Amazon Linux AMI as Amazon Linux yet doesn't have chrome. Thank you.

**Comment by dotneet** [comment]
Possibly chromy can. But I have not try this.

## Attach to the headless shell that is launched in advance.

```js
new Chromy({
  launchBrowser: false
})
```

## Launch the headless shell with chromy

```js
new Chromy({
  chromePath: '/path_to/headless_shell_executable'
})
```

**Comment by kiran-redhat** [comment]
Thanks for quick help @dotneet , managed to run chrome headless-shell with chromy (from BackstopJS) but wondering how to pass proxy & proxy-type to chromy?

**Comment by dotneet** [comment]
@kiran-redhat 
Would `chromeFlags` be your help?

```js
new Chromy({
  chromeFlags: [' --proxy-server="http://proxyhost:8080"']
})
```

**Comment by kiran-redhat** [comment]
@dotneet thank you.. it works without double quotes 
`chromeFlags: [' --proxy-server=http://proxyhost:8080']`
