### ISSUE TITLE
Color rendering inconsistent across different monitor configurations

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#65]
In this example there is a large green area on the screen. When referenced on my 72ppi external monitor then tested with my retina laptop, I get the following diff where all areas of color are slightly different...   (It's hard to see but even the pink color is slightly different and causing a diff)

![image](https://user-images.githubusercontent.com/447033/29723195-83dd27f0-8978-11e7-863b-b45612db85af.png)

**Comment by dotneet** [comment]
What if add '--disable-gpu' to chromeFlags?

**Comment by garris** [comment]
I will try that and let you know.

**Comment by garris** [comment]
YES!!!!!!!!!!    💯 ⚡️✨

This is great!   Thank you!
