### ISSUE TITLE
FEATURE: Export chrome-remote-interface fundamental API.

### ISSUE THREAD

**Issue by holmescn** [OnetapInc/chromy#66]
Chromy is great! It significantly reduce the chrome-remote-interface's complex API. But sometimes, it may lack some feature that is supported in chrome-remote-interface. In order to simplify the API of Chromy, I suggest to export the client's `send` and `on` API. Then we can do tricky thing bypass the limitation of Chromy API.

**Comment by dotneet** [comment]
Hi @holmescn,
Thank you for suggesting great idea!
exporting `send` API will be supported!
`on` API is already supported but I forgot to document it so I'll add it to readme.md later.

**Comment by dotneet** [comment]
I've published 0.5.3@alpha and this version supports send method.
0.5.x series will be published after chrome61 becomes a stable version.

**Comment by garris** [comment]
@dotneet I have a crazy question... 

Theoretically,   Is it possible to instantiate a Puppeteer instance using this hook?

**Comment by dotneet** [comment]
@garris send() calls DevTools protocol directly. So cannot do something that you think probably.
