### ISSUE TITLE
Keep browser session, cookies and data

### ISSUE THREAD

**Issue by fausto1124** [OnetapInc/chromy#67]
Hi, i wanna know how can i let chromy leave all the session, cookies and data when it closes. I know its using chrome-launcher to launch chrome with the options and flags but i dont know where and what to change to let all the sessions variables, cookies and other data for future launchs.
I have been searching in the code but i dont know what to change.

Thanks!

**Comment by dotneet** [comment]
Hi @fausto1124,

chrome-launcher uses a temporary directory as a data directory, it means that all data is removed every time. to persist a data, `userDataDir` option in chromy can be used.

**Comment by fausto1124** [comment]
@dotneet Thanks! That worked!
