### ISSUE TITLE
How to capture 'body' for different pages without changing width and height

### ISSUE THREAD

**Issue by kiran-redhat** [OnetapInc/chromy#68]
Hey @dotneet 

Let's say page 1 is of height 3000px and page 2 is of height 5000px. And I have used following flags to test page 1 and page 2: 

`let chromy = new Chromy({
    chromeFlags: ['--disable-gpu', '--force-device-scale-factor=1', '--window-size={1920},{4000}]
  }).chain();`

and used `chromy.screenshot()` to take screenshot of `body`.

Issue 1:  1000px of height cut down for page 1 
Issue 2: 1000px of empty space (height) is displayed  for page 2.

Related issue: https://github.com/garris/BackstopJS/issues/532  . What is the best approach towards fixing this?

**Comment by dotneet** [comment]
Hi @kiran-redhat,

Please test it.
I've changed the parameter of window-size.

```bash
let chromy = new Chromy({ chromeFlags: ['--disable-gpu', '--force-device-scale-factor=1', '--window-size=1920,4000'] }).chain()
```

**Comment by dotneet** [comment]
@kiran-redhat Sorry, I misunderstood.
Could you post a full example?
screenshot() take a screenshot of viewport, not body element.
If you want to take a screenshot of the body element, please use `screenshotSelector('body')`.

With BackstopJS, body selector is the special selector. If you specify `body` to `selectors` in backstop.json BackstopJS uses .screenshot(), So, as garris mentioned it, you could use `document` to take a screenshot of `body` element.
https://github.com/garris/BackstopJS/blob/master/core/util/runChromy.js#L505

When you specify `document` in backstop.json, is the result same with `body`?

**Comment by kiran-redhat** [comment]
When you specify document in backstop.json, is the result same with body? Yes.

Following is my script, am expecting to see entire `a-page` being captured for `screenshotSelector`

`let chromy = new Chromy({
  chromeFlags: ['--disable-gpu', '--force-device-scale-factor=1', '--window-size=1366,4000']
});

chromy.chain()
  .goto('https://developer.amazon.com/')
  .screenshot()
  .result((png) => {
    fs.writeFileSync('screenshot.png', png)
  })
  .screenshotSelector("#a-page")
  .result((png) => {
    fs.writeFileSync('screenshotSelector_a-page.png', png)  //Here am expecting to see entire 'a-page' but only visible part of screen is captured.
  })
  .screenshotDocument() 
  .result((png) => {
    fs.writeFileSync('screenshotDocument.png', png)
  })
  .end()
  .then(_ => chromy.close())
  .catch(e => {
    console.log(e)
    chromy.close()
  });`

**Comment by garris** [comment]
FWIW:  these are the methods used when various *magic* selectors are used...  Hope this helps.  Also, using `body` is deprecated in backstop, using `viewport` is recommended.

https://github.com/garris/BackstopJS/blob/master/core/util/runChromy.js#L502-L527

**Comment by kiran-redhat** [comment]
yup, I have changed from body to viewport which seems to be using
chromy.screenshot(), still the issue remains.

On Sep 6, 2017 5:14 PM, "Garris" <notifications@github.com> wrote:

FWIW: these are the methods used when various *magic* selectors are used...
Hope this helps. Also, using body is deprecated in backstop, using viewport
is recommended.

https://github.com/garris/BackstopJS/blob/master/core/
util/runChromy.js#L502-L527

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OnetapInc/chromy/issues/68#issuecomment-327376861>, or mute
the thread

**Comment by dotneet** [comment]
@kiran-redhat Thanks for full example.

> Question1: please see below screenshot, screenshot being captured before all the data is loaded
.goto() doesn't ensure that all data is loaded but ensure that onload event is fired. so you can use .wait(selector) or .wait(function) to wait for loading the data that you want.

> Question2: Here am expecting to see entire 'a-page' but only visible part of screen is captured.
In my environment, only header navigation is not captured. Is this same result with you?
If so, this is expected result as specification. For now, the element that has fixed and absolute position is not included in calculation for capture area.
Note: a-page has 70px of margin. you can confirm that in elements pane of chrome developer tools.

> Question3: Here am expecting to see entire document as image but only visible part is captured.
In my environemt, only footer area(.lower-footer) is not displayed. same result? If so, this is a known bug that is caused when body has a margin. to realize full-screen capturing, chromy emulate a window height based on `document.body.scrollHeight`. So the margin of body causes mismatch between actual full-screen height and emulated screen height. Latest chrome has the feature that take a full-screenshot and the feature get around this problem. I'll investigate this problem by studying chrome source code.

**Comment by kiran-redhat** [comment]
Question 2: 
`In my environment, only header navigation is not captured. Is this same result with you?` No. Only visible part of "#a-page" is being captured

Question 3: 
`In my environemt, only footer area(.lower-footer) is not displayed. same result?` No. Only visible part of is being captured

**Comment by dotneet** [comment]
does "visible part" mean same area of screenshot()?
Please tell me your environment: node version, chrome version, OS.

**Comment by kiran-redhat** [comment]
npm: 3.10.10
node: v6.11.2
chrome: 61
OS: Amazon Linux AMI

Sorry, haven't explained clearly before: visible part means when we see chrome in 'response' mode by setting 1366x4000 size as per below screenshot:

![image](https://user-images.githubusercontent.com/17115939/30144873-0637c944-93e2-11e7-91f3-b27f2e84f89e.png)

**Comment by dotneet** [comment]
Thanks! I understood. 
I'll try to reproduce with same environment later.

**Comment by kiran-redhat** [comment]
To clear some things out, I've tested on Amazon Linux AMI & Windows 10 following is what happening:

Summary: if you want to avoid reading following: Issue is chromy.screenshotSelector()  & chromy.screenshotDocument() taking only visible part (attached screenshot) on Amazon Linux AMI with Chrome 61.


**Script used:** 
`let chromy = new Chromy({
  chromeFlags: ['--disable-gpu', '--force-device-scale-factor=1', '--window-size=1366,4000']
});

chromy.chain()
  .goto('https://developer.amazon.com/')
  .screenshot()
  .result((png) => {
  fs.writeFileSync('screenshot.png', png) 
  })
  .screenshotSelector(".lower-footer")
  .result((png) => {
  fs.writeFileSync('screenshotSelector_lower-footer.png', png) 
  })
  .screenshotDocument()
  .result((png) => {
  fs.writeFileSync('screenshotDocument.png', png)
  })
.end()
  .then(_ => chromy.close())
.catch(e => {
  console.log(e)
chromy.close()
});`

**Windows 10, 64 Bit, Chrome 60, Node 6.11.10 & npm 3.10.10:**: 
1. chromy.screenshot() : As expected (takes visible part which is similar when you set 1366x4000 in chrome responsive mode - Below attached screenshot is for what I mean by 'visible part' :) )
2. chromy.screenshotSelector() : As expected (takes asked selector)
3. chromy.screenshotDocument() : As you said it missed to capture .lower-footer (takes rest)

**Amazon Linux AMI, x86_64, Chrome 61(https://github.com/adieuadieu/serverless-chrome/blob/develop/packages/lambda/chrome/chrome-headless-lambda-linux-x64.zip), Node 6.11.2 & npm 3.10.10:**: 
1. chromy.screenshot() : As expected (takes visible part which is similar when you set 1366x4000 in chrome responsive mode - Below attached screenshot is for what I mean by 'visible part' :) )
2. chromy.screenshotSelector() : **Not as expected (take only visible part)**
3. chromy.screenshotDocument() : **Not as expected (take only visible part)**
![image](https://user-images.githubusercontent.com/17115939/30189317-27586d2c-9487-11e7-8d9d-d16656e54b0f.png)

**Comment by dotneet** [comment]
@kiran-redhat maybe the headless_shell that you used does not have the chrome61 features that is required by chormy. that zip file is created 3 months ago and its useragent exactly inidicates v61, it means that is created from latest chromium source code in that time. So that headless_shell is not including chrome61 features.
I recommend you to use a [docker image](https://github.com/yukinying/chrome-headless-browser-docker) or own build headless_shell built from latest chromium code.

**Comment by dotneet** [comment]
Unfortunately, the headless_shell built from latest chromium code seems not to resolve the problems perfectly. `.screenshotDocument()` takes only visible part. but `.screenshotSelector()` works well. If docker can be used in your environment, it's worth to try.

**Comment by kiran-redhat** [comment]
@dotneet , thank you for your time, really appreciate it. I will try https://github.com/adieuadieu/serverless-chrome/pull/66 before meantime, would you be able to share 61 headless_shell that you've built? :)

**Comment by dotneet** [comment]
@kiran-redhat 
ok, you can download the headless_shell from here:
https://www.dropbox.com/s/4asiqs2tfxsj0lx/headless_shell?dl=0

**Comment by kiran-redhat** [comment]
I've tried your 61 also 63(https://github.com/adieuadieu/serverless-chrome/pull/66): 
`.screenshotDocument()` takes everything but .lower-footer
`.screenshot()` take visible part
`screenshotSelector()` takes asked selector

For now, I will use new 61 which solves my problem (takes screenshot for selector). Thank you @dotneet .

**Comment by kiran-redhat** [comment]
@dotneet 
To give some context :) .
Question3: Here am expecting to see entire document as image but only visible part is captured.
[you answer]: In my environemt, only footer area(.lower-footer) is not displayed. same result? If so, this is a known bug that is caused when body has a margin. to realize full-screen capturing, chromy emulate a window height based on document.body.scrollHeight. So the margin of body causes mismatch between actual full-screen height and emulated screen height. Latest chrome has the feature that take a full-screenshot and the feature get around this problem. I'll investigate this problem by studying chrome source code.

I am seeing this issue even in chrome version 64. Any suggestion to get around with this?

**Comment by dotneet** [comment]
Sorry, I don't have idea for now.
When I have a time I try to investigate that problem with latest chrome and chromy.
