### ISSUE TITLE
pdf() doesn't work for me

### ISSUE THREAD

**Issue by nthsense** [OnetapInc/chromy#7]
The pdf example doesn't work for me - disabling the "catch", I get the following error in the console:

Error: PrintToPDF is not implemented

Using Chrome Version 59.0.3071.86 (Official Build) (64-bit)

**Comment by dotneet** [comment]
@nthsense 

I was able to reproduce that problem with visible mode.
Perhaps Chome doesn't support PrintToPDF() without headless mode currently.

**Comment by nthsense** [comment]
@dotneet Confirmed with Chrome Version 61.0.3131.0 (Official Build) canary (64-bit).  However, with Version 59.x, it doesn't work in either mode for me.

**Comment by dotneet** [comment]
Thank you for reporting.
I'll add note about this to README.

**Comment by dotneet** [comment]
If you have any questions reopen this issue or create new issue.
