### ISSUE TITLE
please add babel-runtime as a prod dependency

### ISSUE THREAD

**Issue by garris** [OnetapInc/chromy#75]
Hi @dotneet!  

We recently had a security audit at my company -- and it was discovered that the NPM module `babel-runtime` is actually needed for chromy at runtime.  _This dependency is added by Babel_ during build and required by babel for runtime polyfills.  In most installation cases this works fine since other packages already declare this package implicitly -- but for chromy to pass our validation it needs to explicitly declare this runtime library in chromy's package.json   (it must be under `dependencies` not `devDependencies`)

Would it be possible to declare this dependency?   

I will try to create a PR to make it easier.  

Cheers.

**Comment by dotneet** [comment]
Hi @garris!

It's ok. I'll wait your PR.

**Comment by dotneet** [comment]
I've published v0.5.5. please check it!

**Comment by garris** [comment]
Ok. we are finally checking this on our infrastructure today.  Will follow up soon.

**Comment by garris** [comment]
Worked in prod!   This is great!   Closing.
