### ISSUE TITLE
General query - what are common test assertions used?

### ISSUE THREAD

**Issue by kensoh** [OnetapInc/chromy#80]
Hi Shinji and guys, may I check from you what are common assertions that you used in your test automation? Eg check that element contains text, check element exists etc. Crowdsourcing inputs for test assertions support for a personal project.

This is not an issue, please feel free to close if irrelevant. In that project I made a wrapper around CasperJS but as CasperJS has no support for visible / headless Chrome, test assertions won't work. Working to address that, for some basic range of assertion scenarios to work with Chrome.

**Comment by dotneet** [comment]
Hi @kensoh, I don't write automation tests for front-end enthusiastically.
Almost tests with DOM in my projects are categorized into the cases that you mentioned as example.

**Comment by kensoh** [comment]
Hi Shinji @dotneet thanks for reply! I see, same for me. I usually only validate that some text or element that is supposed to appear after my actions really appear. But I don't work on visual regression as frontend designs often change. I'll close the issue, thank you :)
