### ISSUE TITLE
Custom User Agent Breaks Version Detection

### ISSUE THREAD

**Issue by ks07** [OnetapInc/chromy#81]
It's possible to set a custom user agent using the `--user-agent=foo` Chrome flag. Doing so breaks Chromy's version detection, as this uses navigator.userAgent. This can cause errors about using an outdated version of chrome and can cause the screenshot method to crash due to using removed CDP methods:

```
[14:40:39] Error: 'Emulation.resetViewport' wasn't found
    at /tmp/headlesschrometest/node_modules/chrome-remote-interface/lib/chrome.js:81:28
```

**Comment by dotneet** [comment]
Hi @ks07, Thank you for reporting.
I've resolved that issue and published new version 0.5.6 just now.
