### ISSUE TITLE
Error: An error has occurred evaluating the script in the browser.ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by kiran-redhat** [OnetapInc/chromy#87]
Getting following errors randomly when used more than one chrome instances , running them from BackstopJS. This is intermittent. Looks like chromy triggering script before browser fully loaded ?

1. "Error: An error has occurred evaluating the script in the browser.ReferenceError: $ is not defined" (I use jQuery to show some elements)
2  WaitTimeoutError: wait() timeout
3. Chromy error: error

**Comment by dotneet** [comment]
When `.goto()` is executed without options, chromy waits until load event is fired.
If the script tag for loading jQuery has `async` or `defer` attribute, you need to wait manually for loading jQuery.
