### ISSUE TITLE
Sharing variable between steps

### ISSUE THREAD

**Issue by gavD** [OnetapInc/chromy#9]
Hello,

Thanks for Chromy, it's really useful :-)

I have been unable to use a shared variable in a wait function:

```javascript
const timestamp = 'release-nnn-' + new Date().toISOString();
let chromy = new Chromy( { chromeFlags: [ '--window-size=1200,960' ] } );
chromy.chain()
    .goto( 'http://devenv/' )
    .click( '#somelink' )
    .wait( '#somecontent' )
    .type( '#titleField', timestamp )
    .wait( function(a,b,c) {
        return document.querySelector( '#titkeField' ).innerText.indexOf(timestamp ) > -1;
    } )
```

I get `ReferenceError: timestamp is not defined`. I tried to follow `examples/define_function.js` to wrap my variable in a function but I couldn't figure out how to get it to work.

Is what I am trying to do possible?

Thanks,
- Gavin

**Comment by gavD** [comment]
I got around this by defining timestamp in a module, and it worked fine.

**Comment by gavD** [comment]
Ah, it seems that actually the problem I have manifests only in the wait function

**Comment by dotneet** [comment]
Hi, @gavD 

The functions passed to wait()/evaluate() are evaluated in browser context.
So the variables and functions defined in Node context is not available.

To pass variable to browser context from Node context, you can use evaluate() like this:

```js
const Chromy = require('chromy')

const timestamp = 'release-nnn-' + new Date().toISOString();
let chromy = new Chromy( { chromeFlags: [ '--window-size=1200,960' ] } );
chromy.chain()
    .goto('http://devenv/')
    .console(msg => console.log(msg))
    .evaluate(`timestamp = '${timestamp}'`)
    .wait(function(a,b,c) {
      console.log(timestamp)
      return true
    })
    .end()
    .then(e => {
      chromy.close()
    })
    .catch(e => {
      console.log(e)
      chromy.close()
    })
```

**Comment by gavD** [comment]
Fantastic, thank you :-)
