### ISSUE TITLE
How to click single element from selector

### ISSUE THREAD

**Issue by ackmanx** [OnetapInc/chromy#91]
I have a list of containers that all have a link in them. I need to click a specific one, such as the first one found, but when I use `chromy.click` it clicks all of them at the same time. We are using chromy 0.5.5.

`chromy.click(".dossier-change-status-link[data-track='Cancel']")`

Is there a way to do this without resorting to an evaluate block, such as:

	chromy.evaluate(() => {
		document.querySelector(".dossier-change-status-link[data-track='Cancel']").click()
	})

**Comment by ackmanx** [comment]
Although very fragile, I at least am able to make a highly-specific selector:

    chromy.click(".appointment:nth-child(3) .appointment-task__list-entry:first-child .dossier-change-status-link[data-track='Reschedule']")

**Comment by dotneet** [comment]
@ackmanx There is currently not a way. If you want a option for picking single element, please implement it and send PR.

**Comment by ackmanx** [comment]
Thanks for the info!
