### ISSUE TITLE
Macos Google Chrome.app with different name silently fails

### ISSUE THREAD

**Issue by eenagy** [OnetapInc/chromy#99]
So we were using backstop.js for doing some visual testing for our team.
One of our testers has `Google Chrome.app` with a different name and the tests were failing for her. 
She had `Google Chrome 2.app` on her computer, not sure how that happened.
After renaming the Chrome, everything worked fine.

Reporting it here, if others are experiencing the same thing. I'm not 100% sure that it was chromy's fault or backstopjs, but I would say it's chromy's responsibility to open and run the tests on Chrome.

Reproduce 
OS: MacOS
Install Chrome, rename it to `Google Chrome 2.app`, try running some tests. It should fail.
Again, didn't debug with the source, please ignore or check and see if it's chromy's bug.

Just leaving this comment here, as others could be experiencing the same.

**Comment by dotneet** [comment]
Hi @eenagy, thank you for reporting.

That's not a bug.
If chrome is not located in default path, a path to chrome must be specified by user.
There are two ways to specify the path.

 - specify [chromePath](https://github.com/OnetapInc/chromy#chromyoptions) option
 - set `CHROME_PATH` env variable

this behavior is depending on [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher).

**Comment by eenagy** [comment]
Oh, you are right @dotneet.

Should have looked more into it. Thanks for the quick reply, will close it as it's not an issue then.
